# Project: tlpi
# Makefile created by Steve Chang
# Date modified: 2024.06.02

LIBNAME = libcrc.a

DIR = crc

SUBDIR =

INCLUDE = \

SRCS = $(wildcard *.c)

OBJDIR = obj

include $(MAKE_RULES)
