# Project: tlpi
# Makefile created by Steve Chang
# Date modified: 2024.06.02

LIBNAME = libmain.a

DIR = src

SUBDIR =

INCLUDE = \
	crc \

SRCS = $(wildcard *.c)

OBJDIR = obj

include $(MAKE_RULES)
